In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("transcripts.csv")
df

,call_id,duration_sec,detected_language,text
0,call_recording_01.wav,14.75,en,"Hello, I'm Sarah Miller. I'm calling to inqui..."

In [36]:
text = """
Speaker 1: "Thank you for calling Horizon Telecom, this is Alex speaking. How can I help you today?"
Speaker 2: "Hi Alex, I just have a question about my current package and my next bill."

Speaker 1: "Of course, I can help with that. May I have your name and account number, please?"
Speaker 2: "It’s John Moore, and my account number is 547812."

Speaker 1: "Thank you, Mr. Moore. I’ve pulled up your account now. What would you like to know about your package or upcoming bill?"
Speaker 2: "I just want to confirm what I’m being charged for this month and make sure my discounts are still active."

Speaker 1: "Absolutely. I can see you’re on the Standard Bundle with your loyalty discount applied. Your next bill is estimated at $79, which includes your package, taxes, and your ongoing discount. There are no extra fees or changes scheduled for this cycle."
Speaker 2: "Okay, great, that’s what I wanted to check."

Speaker 1: "Is everything working well with your internet and mobile service at the moment?"
Speaker 2: "Yes, everything’s working fine, no issues."

Speaker 1: "That’s great to hear. Just so you know, your discount is confirmed for the next 12 months, and if your usage changes, we can always review your plan to keep it aligned with what you need."
Speaker 2: "Good to know, thanks."

Speaker 1: "You’re welcome. Is there anything else on your account or services that you’d like me to review while you’re on the line?"
Speaker 2: "No, that’s all. You’ve answered my questions."

Speaker 1: "I’m glad I could help, Mr. Moore. Thank you for being a Horizon Telecom customer. Have a great day."
Speaker 2: "You too, thanks. Bye."
"""

In [37]:
row = ["Not a call recording", "no time", "en", text]
df.loc[len(df)] = row
df

,call_id,duration_sec,detected_language,text
0,call_recording_01.wav,14.75,en,"Hello, I'm Sarah Miller. I'm calling to inqui..."
1,Not a call recording,no time,en,"Speaker 1: ""Good afternoon, thank you for call..."
2,Not a call recording,no time,en,"\nSpeaker 1: ""Thank you for calling Horizon Te..."
3,Not a call recording,no time,en,"\nSpeaker 1: ""Thank you for calling Horizon Te..."
4,Not a call recording,no time,en,"\nSpeaker 1: ""Thank you for calling Horizon Te..."
5,Not a call recording,no time,en,"\nSpeaker 1: ""Thank you for calling Horizon Te..."
6,Not a call recording,no time,en,"\nSpeaker 1: ""Thank you for calling Horizon Te..."

In [38]:
OUTPUT_CSV = "transcripts.csv"
df.to_csv(OUTPUT_CSV, index=False)